// Menu Related
export const TOGGLE_SIDE_MENU = "TOGGLE_SIDE_MENU";

// Modal Related
export const TOGGLE_MODAL = "TOGGLE_MODAL";

// Auth Related
export const MOUNT_LOGIN_MODAL = "MOUNT_LOGIN_MODAL";
export const UNMOUNT_LOGIN_MODAL = "UNMOUNT_LOGIN_MODAL";
export const HANDLE_LOGIN = "HANDLE_LOGIN";
export const HANDLE_LOGOUT = "HANDLE_LOGOUT";
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
export const LOGIN_UNSUCCESSFUL = "LGOIN_UNSUCCESSFUL";
export const LOGOUT_SUCCESSFUL = "LOGOUT_SUCCESSFUL";
export const LOGOUT_UNSUCCESSFUL = "LOGOUT_UNSUCCESSFUL";
export const CLEAR_EMAIL_ERROR = "CLEAR_EMAIL_ERROR";
export const CLEAR_PASSWORD_ERROR = "CLEAR_PASSWORD_ERROR";

//Admin Users Related
export const MOUNT_ADMINUSERS_CONTAINER = "MOUNT_ADMINUSERS_CONTAINER";
export const UNMOUNT_ADMINUSERS_CONTAINER = "UNMOUNT_ADMINUSERS_CONTAINER";

//Admin Posts Related
export const MOUNT_ADMINPOSTS_CONTAINER = "MOUNT_ADMINUSERS_CONTAINER";
export const UNMOUNT_ADMINPOSTS_CONTAINER = "UNMOUNT_ADMINPOSTS_CONTAINER";

// Admin Images Related
export const MOUNT_ADMINIMAGES_CONTAINER = "MOUNT_ADMINIMAGES_CONTAINER";
export const UNMOUNT_ADMINIMAGES_CONTAINER = "UNMOUNT_ADMINIMAGES_CONTAINER";

// Admin Dashboard Related
export const MOUNT_ADMINDASHBOARD_CONTAINER = "MOUNT_ADMINDASHBOARD_CONTAINER";
export const UNMOUNT_ADMINDASHBOARD_CONTAINER = "UNMOUNT_ADMINDASHBOARD_CONTAINER";

// Admin Tags Related
export const MOUNT_ADMINTAGS_CONTAINER = "MOUNT_ADMINTAGS_CONTAINER";
export const UNMOUNT_ADMINTAGS_CONTAINER = "UNMOUNT_ADMINTAGS_CONTAINER";

// Admin Categories Related
export const MOUNT_ADMINCATEGORIES_CONTAINER = "MOUNT_ADMINCATEGORIES_CONTAINER";
export const UNMOUNT_ADMINCATEGORIES_CONTAINER = "UNMOUNT_ADMINCATEGORIES_CONTAINER";

// Key Related
export const GENERATE_KEYS = "GENERATE_KEYS";


